(()=>{'use strict';
const countries=[
['CAN','🇨🇦','カナダ',20,23],['USA','🇺🇸','アメリカ',19,34],['MEX','🇲🇽','メキシコ',20,46],['BRA','🇧🇷','ブラジル',33,64],['GBR','🇬🇧','イギリス',45,29],['FRA','🇫🇷','フランス',47,38],['DEU','🇩🇪','ドイツ',51,32],['ESP','🇪🇸','スペイン',43,46],['ITA','🇮🇹','イタリア',51,43],['TUR','🇹🇷','トルコ',58,42],['RUS','🇷🇺','ロシア',73,23],['CHN','🇨🇳','中国',77,41],['JPN','🇯🇵','日本',88,43],['IND','🇮🇳','インド',69,52],['SAU','🇸🇦','サウジアラビア',59,53],['KOR','🇰🇷','韓国',84,51],['IDN','🇮🇩','インドネシア',79,66],['AUS','🇦🇺','オーストラリア',86,79],['ZAF','🇿🇦','南アフリカ',54,79]
].map(([id,flag,name,x,y])=>({id,flag,name,x,y}));
const byId=Object.fromEntries(countries.map(c=>[c.id,c]));
const types={communication:['Communication','#55e7ff','通信'],proposal:['Proposal','#28c4ed','提案'],agreement:['Agreement','#7cfa45','合意'],rejection:['Rejection','#ff515b','拒否'],logistics:['Logistics (Dispatch)','#ffcc37','物流'],arrival:['Arrival','#ffdf7a','到着'],risk:['Shortage / Risk','#ff658a','不足・リスク'],mutation:['World Mutation','#c487ff','世界の変化']};
const examples=[['JPN','CHN','proposal'],['TUR','DEU','communication'],['IDN','AUS','logistics'],['IND','SAU','proposal'],['USA','GBR','communication'],['CHN','JPN','agreement'],['BRA','ZAF','logistics'],['RUS','TUR','rejection'],['AUS','JPN','arrival'],['JPN','IND','communication'],['CAN','FRA','agreement'],['KOR','JPN','mutation']];
const $=id=>document.getElementById(id), stage=$('world-stage');let turn=6,world='A',selected='JPN',speed=1,playing=false,timer=null,eventIndex=0;
const row=(label,value)=>`<div class="stat-row"><span>${label}</span><b>${value}</b></div>`;
$('legend').innerHTML=Object.entries(types).map(([kind,[label,color]])=>`<div class="legend-item" data-kind="${kind}" style="--event-color:${color}"><i class="legend-line"></i>${label}</div>`).join('');
const bust='<svg viewBox="0 0 40 40" aria-hidden="true"><defs><linearGradient id="bustShade" x2="1" y2="1"><stop stop-color="#d9f6ff"/><stop offset=".55" stop-color="#68869c"/><stop offset="1" stop-color="#0a1926"/></linearGradient></defs><path fill="url(#bustShade)" d="M15 7Q20 3 25 7L26 14 24 20 23 22 23 25 32 29 35 38H5L8 29 17 25 17 22 15 20 14 14Z"/><path fill="#07121d" d="M16 25 20 29 24 25 29 29 25 39H15L11 29Z"/><path stroke="#86bbc9" fill="none" stroke-width=".6" d="m16 25 4 4 4-4m-4 4v9"/></svg>';
countries.forEach(c=>{const b=document.createElement('button');b.className='map-node';b.style.setProperty('--x',c.x+'%');b.style.setProperty('--y',c.y+'%');b.dataset.country=c.id;b.setAttribute('aria-label',c.name+' '+c.id+' の詳細');b.innerHTML=bust.replaceAll('bustShade','bustShade-'+c.id)+`<span class="node-label"><span class="flag">${c.flag}</span>${c.id}</span>`;b.onclick=()=>{selected=c.id;renderSelection()};$('nodes').append(b)});
function events(){if(!turn)return[];let start=turn===6?0:(turn-1)%examples.length;const list=Array.from({length:3},(_,i)=>{const e=examples[(start+i)%examples.length];return {from:e[0],to:e[1],type:e[2],world:'A'}});if(world==='B'||world==='compare'){const other=list.map((e,i)=>({...e,type:i===0?'agreement':i===1?'rejection':e.type,world:'B'}));return world==='B'?other:[...list,...other]}return list}
function routePath(e){const a=byId[e.from],b=byId[e.to],ax=a.x*10,ay=a.y*5,bx=b.x*10,by=b.y*5;return `M${ax} ${ay} Q${(ax+bx)/2} ${Math.min(ay,by)-Math.min(90,Math.abs(bx-ax)*.16+25)} ${bx} ${by}`}
function renderRoutes(es){const trails=turn?examples.slice(4,11).map(([from,to,type])=>({from,to,type})):[];$('routes').innerHTML=trails.map(e=>`<path class="context-route" style="--event-color:${types[e.type][1]}" d="${routePath(e)}"/>`).join('')+es.map((e,i)=>{const color=e.world==='B'&&world==='compare'?'#c487ff':types[e.type][1];const path=routePath(e);return `<g style="--event-color:${color}"><path id="path-${i}" class="route ${e.type}" d="${path}"/><circle class="signal" r="${e.type==='logistics'?3:2}"><animateMotion dur="${(3+i*.25)/speed}s" repeatCount="indefinite" path="${path}"/></circle></g>`}).join('');if(!playing)$('routes').pauseAnimations();else $('routes').unpauseAnimations()}
function renderSelection(){const c=byId[selected],es=events(),e=es.find(e=>e.from===selected||e.to===selected);document.querySelectorAll('.map-node').forEach(n=>{n.classList.toggle('selected',n.dataset.country===selected);n.setAttribute('aria-pressed',String(n.dataset.country===selected))});$('selectedFlag').textContent=c.flag;$('selectedCode').textContent=c.id;const content=row('Status',e?'<span class="active-word">Active</span>':'Standby')+row('Current Action',e?types[e.type][0]:'—')+row('Counterpart',e?(e.from===selected?e.to:e.from):'—')+row('World',world==='compare'?'A / B':world)+row('Source','Design sample');$('selectedStats').innerHTML=content;$('dialogTitle').textContent=c.flag+' '+c.name+' · '+c.id;$('dialogStats').innerHTML=content}
function render(){const es=events(),e=es[eventIndex%Math.max(1,es.length)];stage.classList.toggle('compare',world==='compare');$('timeline').value=turn;$('turnTitle').textContent=`TURN ${String(turn).padStart(2,'0')} / DAY ${turn*7}`;$('turnOutput').textContent=`TURN ${turn} / 13`;$('eventDay').textContent=`TURN ${String(turn).padStart(2,'0')} · DAY ${turn*7}`;const statNames=[['Active Events',es.length],['Communications',es.filter(x=>x.type==='communication').length],['Proposals',es.filter(x=>x.type==='proposal').length],['Agreements',es.filter(x=>x.type==='agreement').length],['Logistics',es.filter(x=>x.type==='logistics').length],['World Mutation',es.filter(x=>x.type==='mutation').length]];$('eventStats').innerHTML=statNames.map(x=>row(...x)).join('');$('eventCount').textContent=e?`EVENT ${eventIndex%es.length+1} / ${es.length}`:'DAY 0 · READY';$('eventPair').textContent=e?`${e.from} → ${e.to}`:'同じ出発点。';$('eventType').textContent=e?types[e.type][0].toUpperCase()+(world==='compare'?' · WORLD '+e.world:''):'';$('eventText').textContent=e?`${byId[e.from].name}から${byId[e.to].name}へ — ${types[e.type][2]}の表示サンプル。`:'PLAYで世界地図上の動きを確認できます。';$('nextEvents').innerHTML=es.filter((_,i)=>i!==eventIndex%es.length).slice(0,3).map((x,i)=>`<div class="next-event"><span><i>${i+1}</i> ${byId[x.from].flag} ${x.from} → ${x.to}</span><span>${types[x.type][2]}</span></div>`).join('')||'<span class="small">待機中</span>';renderRoutes(es);renderSelection()}
function pause(){playing=false;clearInterval(timer);timer=null;stage.classList.remove('playing');$('play').setAttribute('aria-pressed','false');$('playState').textContent='PAUSED';$('routes').pauseAnimations()}
function play(){if(turn>=13){turn=0;eventIndex=0}clearInterval(timer);playing=true;stage.classList.add('playing');$('play').setAttribute('aria-pressed','true');$('playState').textContent='PLAYING';render();timer=setInterval(()=>{const count=events().length;eventIndex++;if(!turn||eventIndex>=count){if(turn>=13){pause();$('playState').textContent='ENDED';return}turn++;eventIndex=0}render()},1800/speed)}
$('play').onclick=play;$('pause').onclick=pause;$('restart').onclick=()=>{pause();turn=0;eventIndex=0;render()};$('timeline').oninput=e=>{pause();turn=Number(e.target.value);eventIndex=0;render()};document.querySelectorAll('[data-world]').forEach(b=>b.onclick=()=>{world=b.dataset.world;eventIndex=0;document.querySelectorAll('[data-world]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{speed=Number(b.dataset.speed);document.querySelectorAll('[data-speed]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));if(playing)play();else render()});$('detailOpen').onclick=()=>$('leaderDialog').showModal();document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});render();
})();
