(()=>{'use strict';const M=window.StageModel,$=id=>document.getElementById(id),app=$('app'),viewport=$('viewport'),byId=Object.fromEntries(M.countries.map(c=>[c.id,c]));let s={turn:6,index:0,world:'A',selected:'JPN',playing:false,speed:1,ended:false},timer=null;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function resize(){const scale=viewport.clientWidth/960;app.style.transform=`scale(${scale})`;viewport.style.height=app.offsetHeight*scale+'px'}new ResizeObserver(resize).observe(viewport);new ResizeObserver(resize).observe(app);resize();
document.querySelectorAll('[data-page]').forEach(a=>{a.href=new URL(a.dataset.page,document.baseURI).href});
$('agentCount').textContent=M.countries.length;$('leaderCount').textContent=M.countries.length;
$('legend').innerHTML=Object.entries(M.types).map(([key,t])=>`<div class="legend-item" data-type="${key}" style="--color:${t.color}"><i class="legend-mark" data-symbol="${t.symbol}"></i>${t.label}</div>`).join('');document.querySelector('.ticks').innerHTML=Array.from({length:7},()=>'<i></i>').join('');
const bust='<svg viewBox="0 0 32 38" aria-hidden="true"><path fill="#bbdfe9" d="M11 7q5-5 10 0l1 7-3 7v3l7 4 2 9H4l2-9 7-4v-3l-3-7z"/><path fill="#091a27" d="m13 23 3 4 3-4 7 5 2 9H4l2-9z"/><path fill="#b7d8df" d="m13 24 3 3 3-3-2 8h-2z"/><path fill="#244152" d="m11 7 3-3 6 1 2 4-1 4-2-5-5 1-3 4z"/></svg>';
M.countries.forEach(c=>{const b=document.createElement('button');b.className='node';b.dataset.id=c.id;b.style.setProperty('--x',c.x+'%');b.style.setProperty('--y',c.y+'%');b.setAttribute('aria-label',`${c.name} ${c.id}の詳細`);b.innerHTML=bust+`<span class="label"><span class="flag">${c.flag}</span>${c.id}</span>`;b.onclick=()=>{s.selected=c.id;renderSelection()};$('nodes').append(b)});
const row=(k,v)=>`<div class="stat"><span>${k}</span><b>${v}</b></div>`;
function current(){const es=M.events(s.turn,s.world);return es[s.index%es.length]}
function path(e){const a=byId[e.from],b=byId[e.to];return `M${a.x*10} ${a.y*5} Q${(a.x+b.x)*5} ${Math.min(a.y,b.y)*5-Math.min(82,Math.abs(a.x-b.x)*1.7+16)} ${b.x*10} ${b.y*5}`}
function renderRoutes(){const es=M.events(s.turn,s.world),now=current(),sv=$('routes');const extra=[['CAN','USA','communication'],['USA','MEX','agreement'],['MEX','BRA','logistics'],['CAN','GBR','proposal'],['GBR','FRA','communication'],['FRA','DEU','agreement'],['DEU','RUS','communication'],['RUS','CHN','logistics'],['CHN','KOR','proposal'],['KOR','JPN','communication'],['JPN','IDN','logistics'],['IDN','AUS','arrival'],['IND','IDN','agreement'],['IND','SAU','proposal'],['SAU','UAE','logistics'],['UAE','IND','communication'],['ZAF','BRA','arrival'],['ZAF','AUS','logistics']];const context=M.sequences[s.world==='B'?'B':'A'].concat(extra).concat(M.countries.filter(c=>c.id!=='JPN').map((c,i)=>['JPN',c.id,['communication','proposal','agreement','rejection','logistics','arrival','risk','mutation'][i%8]])).map(([from,to,type])=>({from,to,type,world:s.world==='B'?'B':'A'}));let markup='<defs><filter id="pointGlow"><feGaussianBlur stdDeviation="2"/></filter></defs>';markup+=context.map((e,i)=>{const a=byId[e.from],b=byId[e.to];const mx=(a.x+b.x)*5,my=(a.y+b.y)*2.5;return `<path class="route context ${e.type}" style="--color:${M.types[e.type].color}" d="${path(e)}"/><text class="vehicle ${i%2?'satellite':'plane'}" x="${mx}" y="${my}">${i%2?'◈':'✈'}</text>`}).join('');markup+=es.map((e,i)=>{const color=e.world==='B'&&s.world==='compare'?'#c583ff':M.types[e.type].color;const d=path(e);return `<g style="--color:${color}"><path class="route ${e.type} ${e.world==='B'&&s.world==='compare'?'world-b':''}" d="${d}"/>${true?`<g class="vehicle ${i%2?'satellite':'plane'}"><text x="${byId[e.from].x*10}" y="${byId[e.from].y*5}">${i%2?'◈':'✈'}</text><animateMotion dur="${(2.7+i*.3)/s.speed}s" repeatCount="indefinite" path="${d}"/></g>`:''}</g>`}).join('');sv.innerHTML=markup;if(s.playing&&!reduced)sv.unpauseAnimations();else{sv.pauseAnimations();sv.setCurrentTime(1.2)}document.querySelectorAll('.node').forEach(n=>{const active=now&&(n.dataset.id===now.from||n.dataset.id===now.to);n.classList.toggle('involved',!!active);n.style.setProperty('--active-color',now?M.types[now.type].color:'#4bd9f0')})}
function renderSelection(){const c=byId[s.selected],e=M.events(s.turn,s.world).find(e=>e.from===c.id||e.to===c.id);$('leaderFlag').textContent=c.flag;$('leaderCode').textContent=c.id;document.querySelectorAll('.node').forEach(b=>{b.classList.toggle('selected',b.dataset.id===c.id);b.setAttribute('aria-pressed',String(b.dataset.id===c.id))});$('leaderStats').innerHTML=row('Status',e?'<span class="active">Active</span>':'Standby')+row('Current Action',e?M.types[e.type].ja:'—')+row('Counterpart',e?(e.from===c.id?e.to:e.from):'—')+row('Related Contract','—')+row('Logistics',e?.type==='logistics'?'Dispatch':'—')+row('World State',M.state(s.turn,s.world==='B'?'B':'A'))}
function renderMetrics(){const a=M.totals(s.turn,'A'),b=M.totals(s.turn,'B');for(const w of ['A','B']){const vals=w==='A'?a:b,other=w==='A'?b:a;$('metrics'+w).innerHTML=M.metrics.map(([key,label],i)=>{const delta=other[i]?Math.round((vals[i]-other[i])/other[i]*100):0;return `<div class="metric" style="--color:${M.types[key].color}"><i>${M.types[key].symbol}</i><span>${label}</span><b>${vals[i]}</b><small>${delta?`<span>${delta>0?'↑':'↓'}</span>${delta>0?'+':''}${delta}%`:'—'}</small></div>`}).join('');$('state'+w).textContent=M.state(s.turn,w);document.querySelector(`[data-card="${w}"]`).classList.toggle('emphasis',s.world===w||s.world==='compare');$('features'+w).innerHTML=`<li>TURN ${s.turn} / DAY ${s.turn*7}の表示サンプル</li><li>通信 ${vals[0]}件・合意 ${vals[2]}件</li><li>物流 ${vals[4]}件・拒否 ${vals[3]}件</li>`}
$('insight1').textContent=`このサンプルでは、欠乏はA ${a[5]}件 / B ${b[5]}件。`;$('insight2').textContent=`拒否 A ${a[3]} / B ${b[3]}、物流 A ${a[4]} / B ${b[4]}。`;$('insight3').textContent=`通信はA ${a[0]}件、B ${b[0]}件として表示。`;$('insight4').textContent=`世界変異の表示サンプル：A ${a[6]} / B ${b[6]}。`}
function renderEvents(){const es=M.events(s.turn,s.world),e=current();$('eventPosition').textContent=es.length?`EVENT ${s.index+1} / ${es.length} · WORLD ${s.world==='compare'?'A / B':s.world}`:'DAY 0 · READY';$('eventTime').textContent=`TURN ${String(s.turn).padStart(2,'0')} / DAY ${s.turn*7}`;$('eventPair').textContent=e?`${e.from} → ${e.to}`:'同じ出発点。';$('eventKind').textContent=e?M.types[e.type].label.toUpperCase():'';$('eventKind').style.color=e?M.types[e.type].color:'';$('eventDescription').textContent=e?`${byId[e.from].name}から${byId[e.to].name}へ、${M.types[e.type].ja}を表示しています。`:'再生すると、Leaderの活動が地図上に現れます。';const upcoming=[];for(let i=s.index+1;i<es.length;i++)upcoming.push({e:es[i],index:i,turn:s.turn});if(s.turn<13)M.events(s.turn+1,s.world).forEach((e,i)=>upcoming.push({e,index:i,turn:s.turn+1}));$('nextList').replaceChildren();upcoming.slice(0,3).forEach((x,i)=>{const b=document.createElement('button');b.innerHTML=`<i>${i+1}</i><span>${byId[x.e.from].flag} ${x.e.from} → ${x.e.to}</span><span>${M.types[x.e.type].label.toUpperCase()}</span>`;b.setAttribute('aria-label',`ターン${x.turn} ${x.e.from}から${x.e.to}の${M.types[x.e.type].ja}`);b.onclick=()=>{pause();s.turn=x.turn;s.index=x.index;render()};$('nextList').append(b)})}
function render(){app.classList.toggle('playing',s.playing);app.classList.toggle('compare',s.world==='compare');$('timeline').value=s.turn;$('timeline').style.setProperty('--progress',(s.turn/13*100)+'%');$('turnOutput').textContent=`TURN ${s.turn} / 13`;$('turnHeading').textContent=`TURN ${String(s.turn).padStart(2,'0')} / DAY ${s.turn*7}`;const es=M.events(s.turn,s.world);$('eventStats').innerHTML=row('Active Events',es.length)+[['Communications','communication'],['Proposals','proposal'],['Agreements','agreement'],['Logistics','logistics'],['World Mutation','mutation']].map(([name,key])=>row(name,es.filter(x=>x.type===key).length)).join('');$('playStatus').textContent=s.playing?'PLAYING':s.ended?'ENDED':'PAUSED';$('play').setAttribute('aria-pressed',String(s.playing));document.querySelectorAll('[data-world]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.world===s.world)));document.querySelectorAll('[data-speed]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.speed===s.speed)));renderRoutes();renderSelection();renderMetrics();renderEvents();resize()}
function pause(){clearInterval(timer);timer=null;s.playing=false;app.classList.remove('playing');$('routes').pauseAnimations();$('play').setAttribute('aria-pressed','false');$('playStatus').textContent=s.ended?'ENDED':'PAUSED'}
function schedule(){clearInterval(timer);timer=setInterval(()=>{s=M.next(s);if(!s.playing)clearInterval(timer);render()},2100/s.speed)}
function play(){if(s.ended){s.turn=0;s.index=0}s.ended=false;s.playing=true;render();schedule()}
$('play').onclick=play;$('pause').onclick=pause;$('restart').onclick=()=>{pause();s.turn=0;s.index=0;s.ended=false;render()};$('timeline').oninput=e=>{pause();s.turn=+e.target.value;s.index=0;s.ended=false;render()};$('nextEvent').onclick=()=>{pause();s=M.next(s);render()};document.querySelectorAll('[data-world]').forEach(b=>b.onclick=()=>{s.world=b.dataset.world;s.index=0;render()});document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{s.speed=+b.dataset.speed;render();if(s.playing)schedule()});$('details').onclick=()=>{const c=byId[s.selected];$('dialogTitle').textContent=`${c.flag} ${c.name} · ${c.id}`;$('dialogContent').innerHTML=$('leaderStats').innerHTML+'<p>このLeaderは画面確認用です。Q1の正式国家identityやTEST IDとは対応させていません。</p>';$('dialog').showModal()};$('evidence').onclick=()=>{$('dialogTitle').textContent='デザインプレビューのデータ';$('dialogContent').innerHTML='<p>国配置・経路・比較数値は、参考画像に合わせた表示サンプルです。研究の凍結データは読み込んでいません。元の画像を画面全体に貼る方式ではなく、地図背景以外はHTML・SVGの画面部品として描画しています。</p>';$('dialog').showModal()};document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});render();
})();
