(function(root){'use strict';
const countries=[['CAN','🇨🇦','カナダ',22,19],['USA','🇺🇸','アメリカ',19,34],['MEX','🇲🇽','メキシコ',18,47],['BRA','🇧🇷','ブラジル',32,66],['GBR','🇬🇧','イギリス',44,25],['FRA','🇫🇷','フランス',46,37],['DEU','🇩🇪','ドイツ',52,29],['ESP','🇪🇸','スペイン',41,47],['ITA','🇮🇹','イタリア',50,44],['TUR','🇹🇷','トルコ',59,44],['RUS','🇷🇺','ロシア',72,19],['CHN','🇨🇳','中国',76,39],['JPN','🇯🇵','日本',89,44],['IND','🇮🇳','インド',70,53],['SAU','🇸🇦','サウジアラビア',57,57],['UAE','🇦🇪','アラブ首長国連邦',64,58],['KOR','🇰🇷','韓国',84,56],['IDN','🇮🇩','インドネシア',79,68],['AUS','🇦🇺','オーストラリア',87,82],['ZAF','🇿🇦','南アフリカ',55,82]].map(([id,flag,name,x,y])=>({id,flag,name,x,y}));
const types={communication:{label:'Communication',ja:'通信',color:'#51e9ff',symbol:'⌁'},proposal:{label:'Proposal',ja:'提案',color:'#29d6fd',symbol:'×'},agreement:{label:'Agreement',ja:'合意',color:'#68f539',symbol:'◇'},rejection:{label:'Rejection',ja:'拒否',color:'#ff514f',symbol:'×'},logistics:{label:'Logistics (Dispatch)',ja:'物流',color:'#ffcf27',symbol:'▰'},arrival:{label:'Arrival',ja:'到着',color:'#ffe87e',symbol:'○'},risk:{label:'Shortage / Risk',ja:'不足・リスク',color:'#ff7197',symbol:'△'},mutation:{label:'World Mutation',ja:'世界変異',color:'#c583ff',symbol:'◇'}};
const sequences={A:[['USA','GBR','communication'],['TUR','DEU','communication'],['JPN','CHN','proposal'],['RUS','TUR','rejection'],['IDN','AUS','logistics'],['BRA','ZAF','proposal'],['IND','SAU','agreement'],['CHN','JPN','communication'],['AUS','JPN','arrival'],['CAN','FRA','communication'],['ZAF','JPN','logistics'],['KOR','JPN','mutation']],B:[['USA','GBR','communication'],['TUR','DEU','agreement'],['JPN','CHN','agreement'],['IND','SAU','proposal'],['IDN','AUS','logistics'],['BRA','ZAF','agreement'],['IND','SAU','logistics'],['CHN','JPN','logistics'],['AUS','JPN','arrival'],['CAN','FRA','communication'],['ZAF','JPN','arrival'],['KOR','JPN','communication']]};
function events(turn,world){if(turn===0)return[];if(world==='compare')return[...events(turn,'A'),...events(turn,'B')];const seq=sequences[world];const start=turn===6?2:(turn-1)*2%seq.length;return Array.from({length:3},(_,i)=>{const [from,to,type]=seq[(start+i)%seq.length];return {from,to,type,world,turn,day:turn*7,id:`${world}-${turn}-${i}`}})}
const bases={A:[132,48,28,20,36,4,0],B:[161,66,42,12,48,2,0]}; const metrics=[['communication','総通信数'],['proposal','提案数'],['agreement','合意数'],['rejection','拒否数'],['logistics','物流実行数'],['risk','欠乏発生数'],['mutation','世界変異']];
function totals(turn,world){return bases[world].map(n=>Math.round(n*turn/6))} function state(turn,world){return turn===0?'Ready':totals(turn,world)[5]>4?'Watch':'Stable'} function next(s){const count=events(s.turn,s.world).length;if(s.turn===0)return{...s,turn:1,index:0};if(s.index+1<count)return{...s,index:s.index+1};if(s.turn>=13)return{...s,playing:false,ended:true};return{...s,turn:s.turn+1,index:0}}
const api={countries,types,sequences,events,metrics,totals,state,next};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.StageModel=api;
})(typeof window!=='undefined'?window:globalThis);
