"""Versioned measurement definitions. No utility function or world controller."""
from .contracts import digest

# ID, meaning, input basis, calculation, unit, aggregation, limits.
_ROWS = [
 ('shortage', 'Essential resource demand and actual fulfillment', ['ledger'],
  'demand=sum(required); fulfilled=sum(consumed); shortage=sum(shortage); rate=fulfilled/demand; cumulative only with complete history',
  'resource stock unit; ratio', 'Within a resource only; world and country retained', 'TURN flow measured at close, not closing inventory; zero demand ratio is not_applicable'),
 ('resource_total', 'Resource accounts including pending output', ['world_state'],
  'domestic + pool + undelivered shipments + production_pending', 'resource stock unit', 'Within resource only', 'Pending output is owned but not usable stock'),
 ('resource_distribution', 'Country stock, demand and shortage distributions', ['world_state/physical/world/accounts', 'ledger'],
  'Maps indexed by country; no equal-distribution target', 'resource stock unit', 'No scalar compression', 'Stock is closing stock; demand and shortage describe the completed TURN'),
 ('self_reliance', 'Physical domestic and external supply components', ['world_state', 'ledger'],
  'stock; demand; available production; max(0,stock-demand); stock//demand; actual external receipts; structural supplier/path counts',
  'resource stock units; turns; counts', 'Country/resource', 'Reserve-only horizon assumes constant demand, no production/loss/external supply; route possibilities are not consent or deliverability'),
 ('autonomy', 'Observed choices and contractual decision boundaries', ['input/catalogue', 'input/consents', 'history/settlement'],
  'Count submitted, conditional and individually feasible submitted choices, catalogue options and explicit refusals; report boundaries separately',
  'counts; categorical facts', 'Country', 'Counts do not rank autonomy; unselected option feasibility and motives are unknown; no inference from silence'),
 ('capacity_damage', 'Available capacity and reduction from maximum operating capacity', ['world_state/physical/capacity_profiles', 'world_state/physical/world/capacities'],
  'maximum_operating=floor(maximum_capacity*utilization_ppm/1000000); deficit=maximum_operating-available',
  'capacity-specific units per TURN', 'Per capacity; no cross-unit sum', 'A capacity deficit is not proof of a particular causal event'),
 ('reference_deviation', 'Signed domestic stock deviation from explicit reference', ['world_state/physical/world/accounts', 'reference checkpoint'],
  'current balance minus reference balance for same country/resource', 'resource stock unit', 'Country/resource', 'Not a desirability score; unknown without explicit compatible reference'),
 ('resilience', 'Observed shortage history and capacity deficit', ['ordered checkpoint ledgers'],
  'first positive shortage, peak, sum; first adjacent decrease after positive shortage; first zero after onset; zero_turn-onset',
  'resource stock units; stock-unit TURN; turns', 'Country/resource', 'Full temporal metrics require contiguous history from TURN1; improvement is not attribution to recovery; recovery mechanism undefined'),
 ('network_reachability', 'Directed structural resource paths at TURN close', ['world_state/network', 'world_state/physical/world/capacities'],
  'Enumerate simple paths with available route, route/shared/source capacity >= resource transport cost',
  'paths; counts', 'Source/destination/resource', 'No stock/consent test or forecast; bounded enumeration fails closed on overflow'),
 ('route_load', 'Dispatch throughput and in-transit resources by route', ['history/settlement/joint_reservations', 'world_state/shipments', 'world_state/network'],
  'load from actual dispatch; utilization=load/capacity; per-resource dispatch cost and outstanding quantity',
  'transport units per TURN; ratio; resource stock units', 'Route/resource', 'Transit does not reserve future throughput; no queue model, waiting unknown; capacities remain shared across resource types'),
 ('shared_load', 'Combined dispatch throughput and transit by capacity group', ['world_state/network', 'world_state/shipments', 'history/settlement'],
  'Sum route dispatch loads in group; divide by group capacity; retain per-resource transit',
  'transport units per TURN; ratio; resource stock units', 'Capacity group/resource', 'Do not sum resource-specific capacity denominators'),
 ('dependency_concentration', 'Structural and observed inbound concentration', ['world_state/network/routes', 'world_state/shipments'],
  'Structural HHI of available inbound route counts grouped by supplier/group; observed HHI of received amounts grouped by supplier/route/group',
  'dimensionless HHI; resource stock unit weights', 'Country/resource', 'HHI is sum of squared shares; empty support is not_applicable, not zero risk; pool is a ledger source, not inferred ultimate origin'),
 ('transaction', 'Intent, individual possibility, settlement, dispatch and receipt', ['history/settlement/choices', 'world_state/shipments'],
  'Copy requested/feasible/settled/dispatched; sum actual arrivals for choice; label full/partial/not_established',
  'resource stock unit', 'Choice; amounts never merged across resources', 'Arrival can lag dispatch; rejection is not conflict'),
 ('transaction_summary', 'Transaction counts and reason-code frequencies', ['history/settlement/choices'],
  'Counts by full/partial/not_established; reason-code occurrence counts', 'counts', 'TURN', 'No normative success rate'),
 ('propagation', 'Potential dependency paths and coincident changes', ['history/events', 'world_state/network', 'ordered checkpoint ledgers'],
  'Directed structural BFS from explicit shock origin; identify first observed shortage increase on path only where adjacent checkpoints exist',
  'event/state/resource/path/turn', 'Origin and reachable node', 'Static possibility and temporal coincidence are not causal identification; no invented cascade'),
 ('conflict_load', 'Conflict burden', [], 'Not computed: no V3 operational definition', 'undefined', 'None', 'Refusal and self-priority are not conflict'),
 ('overreaction', 'Overreaction', [], 'Not adopted: reference policy/required response undefined', 'undefined', 'None', 'Do not copy V1 scoring'),
 ('underreaction', 'Underreaction', [], 'Not adopted: reference policy/required response undefined', 'undefined', 'None', 'Do not copy V1 scoring'),
]
DEFINITIONS = {row[0]: dict(zip(('metric_id','definition','inputs','calculation','unit','aggregation','known_limits'), row),
                          introduced_version='v3-observation-1') for row in _ROWS}
DEFINITIONS_DIGEST = digest(DEFINITIONS)
